### ISSUE TITLE
请问怎么计算 map ?

### ISSUE THREAD

**Issue by ANamTHONY** [Jittor/JDet#36]

**Comment by cxjyxxme** [comment]
在跑完valid之后会自动计算的，计算的函数是在这里实现的：https://github.com/Jittor/JDet/blob/master/python/jdet/data/dota.py#L85

**Comment by ANamTHONY** [comment]
哦好的，谢谢，之前一直没跑valid没看到

**Comment by cxjyxxme** [comment]
不客气，那我把这个issue关了？

**Comment by ANamTHONY** [comment]
OK
